<?php
$EM_CONF[$_EXTKEY] = array(
    'title' => 'Page Browser',
    'description' => 'Quickly insert paginations (prev/next menus) in sections of your website',
    'category' => 'plugin',
    'shy' => 0,
    'version' => '3.0.0',
    'dependencies' => '',
    'conflicts' => '',
    'priority' => '',
    'loadOrder' => '',
    'module' => '',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'modify_tables' => '',
    'clearcacheonload' => 0,
    'lockType' => '',
    'author' => 'Torsten Schrade',
    'author_email' => 'Torsten.Schrade@adwmainz.de',
    'author_company' => '',
    'CGLcompliance' => '',
    'CGLcompliance_note' => '',
    'constraints' => array(
        'depends' => array(
            'typo3' => '7.6.0-8.7.99',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
    '_md5_values_when_last_written' => 'a:20:{s:13:"CHANGELOG.txt";s:4:"39d9";s:21:"ext_conf_template.txt";s:4:"30ee";s:12:"ext_icon.gif";s:4:"aea2";s:17:"ext_localconf.php";s:4:"a34a";s:14:"ext_tables.php";s:4:"49c4";s:8:"TODO.txt";s:4:"d41d";s:14:"doc/manual.sxw";s:4:"46a8";s:21:"lang/locallang_db.xml";s:4:"c9e2";s:31:"pi1/class.tx_cagpagebrowser.php";s:4:"d495";s:19:"res/pagebrowser.gif";s:4:"d335";s:37:"static/common/entrylink/constants.txt";s:4:"60d2";s:33:"static/common/entrylink/setup.txt";s:4:"d59b";s:23:"static/v1/constants.txt";s:4:"872b";s:19:"static/v1/setup.txt";s:4:"7adb";s:35:"static/v1/pagenumbers/constants.txt";s:4:"e53b";s:31:"static/v1/pagenumbers/setup.txt";s:4:"0894";s:23:"static/v2/constants.txt";s:4:"38ff";s:19:"static/v2/setup.txt";s:4:"0ded";s:36:"static/v2/treeprevnext/constants.txt";s:4:"5cf3";s:32:"static/v2/treeprevnext/setup.txt";s:4:"526c";}',
    'suggests' => array(),
);
